[book]
src = "frontend"
title = "SUPERTITLE"

[output.html]
no-section-label = true
# additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
git-repository-url = "https://github.com/a-t-0/Studying-Companies-With-Weaviate"

[output.html.fold]
enable = true
